config/routes.rb
Ma::Application.routes.draw do
  resources :activities

  resources :observations

  get "feeds/index"

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  attr_accessible :disable, :main_url, :media, :memo, :organizer_id, :sub_url, :title
end

app/models/observation.rb
class Observation < ActiveRecord::Base
  attr_accessible :disable, :media, :title, :url
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @activities }
    end
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    @activity = Activity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/new
  # GET /activities/new.json
  def new
    @activity = Activity.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/1/edit
  def edit
    @activity = Activity.find(params[:id])
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(params[:activity])

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render json: @activity, status: :created, location: @activity }
      else
        format.html { render action: "new" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /activities/1
  # PUT /activities/1.json
  def update
    @activity = Activity.find(params[:id])

    respond_to do |format|
      if @activity.update_attributes(params[:activity])
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to activities_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/feeds_controller.rb
# encoding: utf-8
class FeedsController < ApplicationController

  require 'net/http'
  require 'rubygems'
  require 'hpricot'
  require 'open-uri'

  def index

    # 監視URLを取得 
    activities = Activity.where("disable = ? ", 0)

    # scraping
    activities.each do |activity|

      doc = Hpricot(open(URI.encode(activity.main_url)).read )

      @arr = []
      (doc/"table.event_table tr").each do |tr| 

        (tr/"td.event_name").each do |elm|
          @arr << elm.inner_html
        end

        (tr/"td.event_date").each { |elm| @arr << elm.inner_html }
        (tr/"td.event_prefecture").each { |elm| @arr << elm.inner_html }
        (tr/"td.event_strength").each { |elm| @arr << elm.inner_html }
        (tr/"td.event_hosts").each { |elm| @arr << elm.inner_html }
        (tr/"td.event_description").each { |elm| @arr << elm.inner_html }

      end

    end

    

    # url = URI.parse('http://kokucheese.com/main/host/%E5%90%8D%E5%8F%A4%E5%B1%8B%E3%81%8A%E3%81%AF%E3%82%88%E3%81%86meeting')
    # req = Net::HTTP::Get.new(url.path)
    # @res = Net::HTTP.start(url.host, url.port) { |http| http.request(req) } 

  end


end

app/controllers/observations_controller.rb
class ObservationsController < ApplicationController
  # GET /observations
  # GET /observations.json
  def index
    @observations = Observation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @observations }
    end
  end

  # GET /observations/1
  # GET /observations/1.json
  def show
    @observation = Observation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @observation }
    end
  end

  # GET /observations/new
  # GET /observations/new.json
  def new
    @observation = Observation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @observation }
    end
  end

  # GET /observations/1/edit
  def edit
    @observation = Observation.find(params[:id])
  end

  # POST /observations
  # POST /observations.json
  def create
    @observation = Observation.new(params[:observation])

    respond_to do |format|
      if @observation.save
        format.html { redirect_to @observation, notice: 'Observation was successfully created.' }
        format.json { render json: @observation, status: :created, location: @observation }
      else
        format.html { render action: "new" }
        format.json { render json: @observation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /observations/1
  # PUT /observations/1.json
  def update
    @observation = Observation.find(params[:id])

    respond_to do |format|
      if @observation.update_attributes(params[:observation])
        format.html { redirect_to @observation, notice: 'Observation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @observation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /observations/1
  # DELETE /observations/1.json
  def destroy
    @observation = Observation.find(params[:id])
    @observation.destroy

    respond_to do |format|
      format.html { redirect_to observations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/observations_helper.rb
module ObservationsHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :organizer_id %><br />
    <%= f.number_field :organizer_id %>
  </div>
  <div class="field">
    <%= f.label :media %><br />
    <%= f.text_field :media %>
  </div>
  <div class="field">
    <%= f.label :main_url %><br />
    <%= f.text_field :main_url %>
  </div>
  <div class="field">
    <%= f.label :sub_url %><br />
    <%= f.text_field :sub_url %>
  </div>
  <div class="field">
    <%= f.label :memo %><br />
    <%= f.text_area :memo %>
  </div>
  <div class="field">
    <%= f.label :disable %><br />
    <%= f.number_field :disable %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<h1>Listing activities</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Organizer</th>
    <th>Media</th>
    <th>Main url</th>
    <th>Sub url</th>
    <th>Memo</th>
    <th>Disable</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @activities.each do |activity| %>
  <tr>
    <td><%= activity.title %></td>
    <td><%= activity.organizer_id %></td>
    <td><%= activity.media %></td>
    <td><%= activity.main_url %></td>
    <td><%= activity.sub_url %></td>
    <td><%= activity.memo %></td>
    <td><%= activity.disable %></td>
    <td><%= link_to 'Show', activity %></td>
    <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
    <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @activity.title %>
</p>

<p>
  <b>Organizer:</b>
  <%= @activity.organizer_id %>
</p>

<p>
  <b>Media:</b>
  <%= @activity.media %>
</p>

<p>
  <b>Main url:</b>
  <%= @activity.main_url %>
</p>

<p>
  <b>Sub url:</b>
  <%= @activity.sub_url %>
</p>

<p>
  <b>Memo:</b>
  <%= @activity.memo %>
</p>

<p>
  <b>Disable:</b>
  <%= @activity.disable %>
</p>


<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>

app/views/feeds/index.html.erb
<h1>Feeds#index</h1>
<p>Find me in app/views/feeds/index.html.erb</p>

<% @arr.each do |elm| %>
  <%= elm %><br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ma</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/observations/_form.html.erb
<%= form_for(@observation) do |f| %>
  <% if @observation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@observation.errors.count, "error") %> prohibited this observation from being saved:</h2>

      <ul>
      <% @observation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :media %><br />
    <%= f.text_field :media %>
  </div>
  <div class="field">
    <%= f.label :disable %><br />
    <%= f.text_field :disable %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/observations/edit.html.erb
<h1>Editing observation</h1>

<%= render 'form' %>

<%= link_to 'Show', @observation %> |
<%= link_to 'Back', observations_path %>

app/views/observations/index.html.erb
<h1>Listing observations</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Url</th>
    <th>Media</th>
    <th>Disable</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @observations.each do |observation| %>
  <tr>
    <td><%= observation.title %></td>
    <td><%= observation.url %></td>
    <td><%= observation.media %></td>
    <td><%= observation.disable %></td>
    <td><%= link_to 'Show', observation %></td>
    <td><%= link_to 'Edit', edit_observation_path(observation) %></td>
    <td><%= link_to 'Destroy', observation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Observation', new_observation_path %>

app/views/observations/new.html.erb
<h1>New observation</h1>

<%= render 'form' %>

<%= link_to 'Back', observations_path %>

app/views/observations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @observation.title %>
</p>

<p>
  <b>Url:</b>
  <%= @observation.url %>
</p>

<p>
  <b>Media:</b>
  <%= @observation.media %>
</p>

<p>
  <b>Disable:</b>
  <%= @observation.disable %>
</p>


<%= link_to 'Edit', edit_observation_path(@observation) %> |
<%= link_to 'Back', observations_path %>